apiVersion: v1
kind: Namespace
metadata:
  name: netology
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-app
  namespace: netology
  labels:
    k8s-app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: my-app
  template:
    metadata:
      name: my-app
      labels:
        k8s-app: my-app
    spec:
      containers:
      - name: my-nginx
        image: docker.io/michail77/image_nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-my
  namespace: netology
  labels:
    k8s-app: my-app
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    k8s-app: my-app
  type: LoadBalancer