name: CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   services:
  #     database:
  #       image: mysql:8.0
  #       env:
  #         MYSQL_ROOT_PASSWORD: password
  #         MYSQL_DATABASE: database
  #       ports:
  #         - 3306:3306
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v3

  #     - name: Execute database migrations
  #       run: bin/console doctrine:migrations:migrate --no-interaction

  #     - name: Run tests
  #       run: make check

  build:
    name: Build
    # needs: test
    runs-on: ubuntu-latest
    steps:
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            docker.io/michail77/image_nginx:latest
            docker.io/michail77/image_nginx:${{ github.sha }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [ test, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: compute.operator/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: 158.160.49.210
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: compute.operator/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/ingress.yaml
            kubernetes/service.yaml
          images: |
            docker.io/michail77/image_nginx:${{ github.sha }}