name: node_app

on: # specify the build to trigger the automated ci/cd
    push:
        branches:
            - "main"
        tag: 
            -v*.*.*    

jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest # specify the build machine
        steps:
            - # checkout to the repository on the build machine
                name: Checkout
                uses: actions/checkout@v4
            - # login to Docker Hub using the secrets provided
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - # create a build kit builder instance
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            - # build the container image and push it to Docker \
                # Hub with the name image-nginx.
                name: Build and push
                uses: docker/build-push-action@v5
                with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: michail77/image-nginx:latest
            
            - name: Configure Kubernetes CLI
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}

            - name: Deploy to Kubernetes via Helm
              run: |
                helm upgrade --install nginx michail77/image-nginx --set image.repository=michail77/image-nginx:latest
                  --kubeconfig=$HOME/.kube/config

