name: node_app

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: michail77/image-nginx:latest
  RELEASE_NAME: nginx-release
  NAMESPACE: netology

jobs:
  build-and-push:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}
      # - name: Build the Docker image
      #   run: docker buildx build --tag ${IMAGE_TAG} .

  deploy:
    needs: build-and-push
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Kubernetes CLI
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install ${{ env.RELEASE_NAME }} ./nginx --set image.repository=${{ env.IMAGE_TAG }} --namespace ${{ env.NAMESPACE }}
            --kubeconfig=$HOME/.kube/config

      # - name: Configure Kubernetes CLI
      #   uses: azure/k8s-set-context@v4
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBECONFIG }}

      # - name: Deploy to Kubernetes with Helm
      #   run: |
      #     helm upgrade --install ${{ env.RELEASE_NAME }} ./nginx --set image.repository=${{ env.IMAGE_TAG }} --namespace ${{ env.NAMESPACE }}
      #       --kubeconfig=$HOME/.kube/config